#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_ACCELERATOR                         101
#define IDR_MANIFEST                            102
#define IDD_DLGMAIN                             104
#define IDM_SELECTALL                           200
#define IDM_EXIT                                201
#define IDC_EDITINPUT                           40000
#define IDC_DEGREES                             40001
#define IDC_RADIANS                             40002
#define IDC_GRADS                               40003
#define IDC_COMBOHISTORY                        40004
#define IDC_EDITRESULT                          40005
#define IDC_BUTTONADDHISTORY                    40006
#define IDC_BUTTON0                             40007
#define IDC_BUTTONMINUS                         40008
#define IDC_BUTTONPLUS                          40009
#define IDC_BUTTONCALC                          40010
#define IDC_BUTTONMULTIPLY                      40011
#define IDC_BUTTONDIVIDE                        40012
#define IDC_BUTTONASIN                          40013
#define IDC_BUTTON1                             40014
#define IDC_BUTTON2                             40015
#define IDC_BUTTON3                             40016
#define IDC_BUTTON4                             40017
#define IDC_BUTTON5                             40018
#define IDC_BUTTON6                             40019
#define IDC_BUTTON7                             40020
#define IDC_BUTTON8                             40021
#define IDC_BUTTON9                             40022
#define IDC_BUTTONSIN                           40023
#define IDC_BUTTONCOS                           40024
#define IDC_BUTTONTAN                           40025
#define IDC_BUTTONDIV                           40026
#define IDC_BUTTONABS                           40027
#define IDC_BUTTONXPOWY                         40028
#define IDC_BUTTONLG                            40029
#define IDC_BUTTONLN                            40030
#define IDC_BUTTONEXP                           40031
#define IDC_BUTTONSQRT                          40032
#define IDC_BUTTONPERC                          40033
#define IDC_BUTTONACOS                          40034
#define IDC_BUTTONATAN                          40035
#define IDC_BUTTONSINH                          40036
#define IDC_BUTTONCOSH                          40037
#define IDC_BUTTONTANH                          40038
#define IDC_BUTTONASINH                         40039
#define IDC_BUTTONACOSH                         40040
#define IDC_BUTTONATANH                         40041
#define IDC_BUTTONROOT                          40042
#define IDC_BUTTONXPOW3                         40043
#define IDC_BUTTONXPOW2                         40044
#define IDC_BUTTONLOGN                          40045
#define IDC_BUTTONLOG2                          40046
#define IDC_BUTTONLOG10                         40047
#define IDC_BUTTONPI                            40048
#define IDC_BUTTONEULER                         40049
#define IDC_BUTTONCLEAR                         40050
#define IDC_BUTTONBRACKET1                      40051
#define IDC_BUTTONBRACKET2                      40052
#define IDC_BUTTONBRACKETS                      40053
#define IDC_BUTTONBIN                           40054
#define IDC_BUTTONOCT                           40055
#define IDC_BUTTONHEX                           40056
#define IDC_BUTTONMOD                           40057
#define IDC_BUTTONCOPY                          40058
#define IDC_BUTTONBITAND                        40059
#define IDC_BUTTONBITOR                         40060
#define IDC_BUTTONBITXOR                        40061
#define IDC_BUTTONBITNOT                        40062
#define IDC_BUTTONBITLEFT                       40063
#define IDC_BUTTONBITRIGHT                      40064
#define IDC_BUTTONPOINT                         40065
#define IDC_STATICHINT                          40066
